[package]
name = "illegal-numbers-check"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
hyper = "1.6.0"
hyper-util = { version = "0.1.10", features = ["tokio"] }
num_cpus = "1.16.0"
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.4"